apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-of-apps-prod
  namespace: team-mdk
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: 'https://kubernetes.default.svc'
  project: app-of-apps
  source:
    helm:
      valueFiles:
        - prod.yaml
    path: .
    repoURL: 'https://github.com/jrdegroot/demo-app-of-apps-deployment.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
