apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-of-apps-prod
  namespace: argocd
spec:
  destination:
    namespace: demo
    server: 'https://kubernetes.default.svc'
  project: app-of-apps
  source:
    helm:
      valueFiles:
        - prod.yaml
    path: .
    repoURL: 'https://github.com/jrdegroot/demo-app-of-apps-deployment.git'
    targetRevision: main
