apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-application-{{ .Values.environment }}
  namespace: argocd # applications vallen onder de argocd namespace
spec:
  project: default
  source:
    repoURL: 'https://github.com/jrdegroot/demo-application-deployment.git'
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - {{.Values.environment}}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
